#!/usr/bin/env python3
"""Prediction = compression: the shortest program wins (Solomonoff / MDL).

The slogan "intelligence is compression" (Solomonoff, Hutter) has a precise core:
the best predictor of a sequence is the *shortest program* that generates it, and
its code length is the sequence's Kolmogorov complexity. This module makes that
concrete WITHOUT any large model — pure numpy on tiny sequences — and is honest
about both edges of the claim:

  * On data that is **statistically random but algorithmically simple** (e.g. a
    linear-congruential PRNG, or the Thue-Morse sequence), a statistical model is
    helpless (~8 bits/byte) while a short-program (MDL) predictor recovers the
    generator from a handful of samples and then predicts the rest for almost
    free. Compression = finding the program statistics can't see.
  * On **genuinely random** data (a cryptographic stream), NO predictor beats
    the entropy — you cannot compress below Shannon / Kolmogorov, and this module
    shows the shortest-program search correctly gives up. Compression is not magic.

Honesty: true Solomonoff induction is *uncomputable* (Kolmogorov complexity is
uncomputable). We approximate it over a small, explicit hypothesis class — which
is exactly what every real compressor does.
"""

from __future__ import annotations

import math

import numpy as np

from .common import Report, header, save_result


# --------------------------------------------------------------------------- #
#  Sequence generators (each is a SHORT program)
# --------------------------------------------------------------------------- #
def lcg_sequence(n: int, a: int = 1103515245, c: int = 12345, m: int = 256,
                 seed: int = 7) -> np.ndarray:
    """Linear-congruential generator mod m: statistically flat, program is tiny."""
    out = np.empty(n, dtype=np.int64)
    x = seed % m
    for i in range(n):
        x = (a * x + c) % m
        out[i] = x
    return out


def thue_morse(n: int) -> np.ndarray:
    """Thue-Morse over {0,1}: t_k = parity of popcount(k). Order-0 balanced,
    yet generated by a one-line program."""
    return np.array([bin(k).count("1") & 1 for k in range(n)], dtype=np.int64)


def periodic_sequence(n: int, block: list[int]) -> np.ndarray:
    return np.array([block[i % len(block)] for i in range(n)], dtype=np.int64)


def random_bytes(n: int, seed: int = 0) -> np.ndarray:
    """Incompressible baseline: uniform random bytes."""
    return np.random.default_rng(seed).integers(0, 256, size=n, dtype=np.int64)


# --------------------------------------------------------------------------- #
#  Statistical predictor: order-k adaptive KT code length (bits)
# --------------------------------------------------------------------------- #
def codelen_statistical(seq: np.ndarray, order: int, alphabet: int) -> float:
    """Total code length under an order-`order` adaptive model with KT (add-1/2)
    smoothing — the code length a good statistical compressor would achieve."""
    counts: dict = {}
    totals: dict = {}
    bits = 0.0
    ctx: tuple[int, ...] = ()
    half = 0.5
    for sym in seq:
        sym = int(sym)
        c = counts.get(ctx)
        if c is None:
            c = np.zeros(alphabet)
            counts[ctx] = c
            totals[ctx] = 0
        p = (c[sym] + half) / (totals[ctx] + half * alphabet)
        bits += -math.log2(p)
        c[sym] += 1
        totals[ctx] += 1
        seq_ctx = tuple(int(x) for x in (ctx + (sym,)))
        ctx = seq_ctx[-order:] if order > 0 else ()
    return bits


def best_statistical_codelen(seq: np.ndarray, alphabet: int,
                             max_order: int = 3) -> tuple[float, int]:
    """Best order-k statistical code length over k = 0..max_order."""
    best = (math.inf, 0)
    for k in range(max_order + 1):
        b = codelen_statistical(seq, k, alphabet)
        if b < best[0]:
            best = (b, k)
    return best


# --------------------------------------------------------------------------- #
#  MDL / shortest-program predictor over an explicit hypothesis class
# --------------------------------------------------------------------------- #
def _egcd(a: int, b: int) -> tuple[int, int, int]:
    if a == 0:
        return b, 0, 1
    g, x, y = _egcd(b % a, a)
    return g, y - (b // a) * x, x


def _inv_mod(a: int, m: int) -> int | None:
    a %= m
    g, x, _ = _egcd(a, m)
    return x % m if g == 1 else None


def infer_lcg(seq: np.ndarray, m: int = 256) -> tuple[int, int] | None:
    """Recover (a, c) of an LCG mod m from the first few samples, then verify it
    reproduces the WHOLE sequence. Returns (a, c) or None. This is Solomonoff in
    miniature: infer the short program from data, then predict at zero cost."""
    if len(seq) < 4:
        return None
    x0, x1, x2 = int(seq[0]), int(seq[1]), int(seq[2])
    denom = (x1 - x0) % m
    inv = _inv_mod(denom, m)
    if inv is None:
        return None
    a = ((x2 - x1) * inv) % m
    c = (x1 - a * x0) % m
    x = x0
    for i in range(1, len(seq)):
        x = (a * x + c) % m
        if x != int(seq[i]):
            return None
    return a, c


def mdl_codelen(seq: np.ndarray, alphabet: int) -> tuple[float, str]:
    """Two-part MDL: shortest (program-bits + data-given-program) over a small
    hypothesis class. Returns (bits, hypothesis_name). Falls back to the best
    statistical model when nothing structural fits (the honest incompressible case)."""
    n = len(seq)
    hyps: list[tuple[float, str]] = []

    # H1: constant symbol.
    if np.all(seq == seq[0]):
        hyps.append((math.log2(alphabet), "constant"))

    # H2: periodic with small period p (store p and one block).
    for p in range(1, min(64, n // 2) + 1):
        if np.array_equal(seq, np.tile(seq[:p], n // p + 1)[:n]):
            hyps.append((math.log2(64) + p * math.log2(alphabet), f"period-{p}"))
            break

    # H3: LCG (recover a,c from the prefix; verify full reproduction).
    if alphabet == 256:
        lcg = infer_lcg(seq, m=256)
        if lcg is not None:
            # describe m (fixed), seed, a, c ~ 4 bytes total.
            hyps.append((4 * 8.0, f"lcg(a={lcg[0]},c={lcg[1]})"))

    # H4: Thue-Morse match (a fixed tiny program).
    if alphabet == 2 and np.array_equal(seq, thue_morse(n)):
        hyps.append((16.0, "thue-morse"))

    # Fallback: no short program fits -> the data IS its own shortest description.
    stat_bits, k = best_statistical_codelen(seq, alphabet)
    hyps.append((stat_bits, f"statistical(order-{k})"))

    return min(hyps, key=lambda t: t[0])


# --------------------------------------------------------------------------- #
#  Demo
# --------------------------------------------------------------------------- #
def demo() -> bool:
    print(header("Prediction = compression: the shortest program wins"))
    report = Report()
    n = 4000

    cases = [
        ("LCG PRNG (looks random, tiny program)", lcg_sequence(n), 256, True),
        ("Thue-Morse (order-0 balanced)", thue_morse(n), 2, True),
        ("period-12 repetition", periodic_sequence(n, list(range(12))), 256, True),
        ("cryptographic-random bytes", random_bytes(n), 256, False),
    ]

    print("\n  sequence                                stat bits/sym   MDL bits/sym   MDL found")
    print("  " + "-" * 84)
    structured_wins = True
    random_incompressible = True
    for name, seq, alph, structured in cases:
        stat_bits, k = best_statistical_codelen(seq, alph)
        mdl_bits, hyp = mdl_codelen(seq, alph)
        stat_bps = stat_bits / n
        mdl_bps = mdl_bits / n
        print(f"  {name:38s}  {stat_bps:>10.4f}    {mdl_bps:>10.5f}    {hyp}")
        if structured:
            # MDL must massively beat statistics on algorithmically-simple data
            structured_wins = structured_wins and (mdl_bps < 0.25 * stat_bps)
        else:
            # on true randomness NOBODY beats ~log2(alphabet); MDL must NOT pretend to
            random_incompressible = random_incompressible and (
                mdl_bps > 0.95 * math.log2(alph) and hyp.startswith("statistical"))

    report.check("shortest-program (MDL) crushes statistics on algorithmic data",
                 structured_wins)
    report.check("on truly random data MDL correctly gives up (~log2 alphabet, no magic)",
                 random_incompressible)

    # The two-part-code view (the exact quantity the Hutter Prize minimises).
    print("\n  Two-part code = |program| + |data given program|  (= what the Hutter Prize scores):")
    seq = lcg_sequence(n)
    mdl_bits, hyp = mdl_codelen(seq, 256)
    naive = n * 8.0
    print(f"   LCG stream, {n} bytes:  raw = {naive:.0f} bits,  "
          f"shortest program = {mdl_bits:.0f} bits ({hyp})  ->  {naive / mdl_bits:.0f}x")
    report.check("recovering the generator compresses the LCG stream >100x",
                 naive / mdl_bits > 100)

    print("\n" + header("CONCLUSION"))
    print("The best model of a sequence is the shortest program that makes it — code")
    print("length equals Kolmogorov complexity. A short-program search compresses")
    print("'random-looking' but simple data by orders of magnitude that no statistical")
    print("model can touch; and on genuinely random data it correctly fails, because no")
    print("codec beats Shannon. (True Solomonoff induction is uncomputable; we approximate")
    print("it over a small hypothesis class — exactly what real compressors do.)")
    print(f"\n{report.summary()}")
    print("ALL CHECKS PASSED" if report.ok else "SOME CHECKS FAILED")

    save_result("06_induction", {
        "lcg_compression_ratio": naive / mdl_bits,
        "all_checks_passed": report.ok,
    })
    return report.ok


if __name__ == "__main__":
    raise SystemExit(0 if demo() else 1)
